name: Test PR

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x]

    steps:
    - name: Checkout the repository
      uses: actions/checkout@master

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install 
    
    - name: Build Package
      run: npm run build

    - name: Run Tests
      run: npm run test

